global.serverUrl = 'http://127.0.0.1:9000'
global.imgServer = 'http://img.twenq.com/'
global.faceUrl = global.imgServer + 'upload/user/avatar/'
global.artimgUrl = global.imgServer + 'upload/artimg/'
global.firendAvatarimgUrl = global.imgServer + 'upload/firend/avatar/'
global.musicServer = 'http://music.twenq.com/'
global.musicCoverUrl = global.musicServer + 'upload/music/cover/'
global.musicResourceUrl = global.musicServer + 'upload/music/resource/'
global.TOKEN_TIME_DAY = 7
global.commentPageSize = 5
global.articlePageSize = 5
global.firendPageSize = 5
global.userManagePageSize = 5
global.MusicPageSize = 10